### ISSUE TITLE
Update _companies/blank-slate-brewing-company.html by Scott LaFollette on 9/27/2016

### ISSUE THREAD

**Issue by madeincincyanon** [madeincincy/madeincincy.github.io#66]
---

date: 2016-09-27T12:30:50.992Z
title: Blank Slate Brewing Company
industry: /companies/brewers-distilleries/
location: ''
image: ''
images: []
links: []
tags: []
author: Scott LaFollette
authorEmail: scott@blankslatebeer.com
created: 2016-09-27T12:30:50.996Z
layout: company

---

**Comment by klcodanr** [comment]
Updated to add more information:

---

date: 2016-09-27T12:30:50.992Z
title: Blank Slate Brewing Company
industry: /companies/brewers-distilleries/
location: '4233 Airport Rd, Cincinnati, OH 45226'
image: 'http://i.imgur.com/SVtcXgm.png'
images: []
links: 
- http://www.blankslatebeer.com/
  tags: 
- craft beer
- brewing
- beer
  author: Scott LaFollette
  authorEmail: scott@blankslatebeer.com
  created: 2016-09-27T12:30:50.996Z
  layout: company

---

<p>
<strong>Blank Slate Brewing Company is one of Cincinnati's newest craft breweries.</strong></p>
<p>
Cincinnati has a rich brewing heritage. Before prohibition there were more than 30 breweries here. Since prohibition, not so much. In recent years there have been the roots of a revolution growing in this town. Craft brewing is making a comeback in Cincinnati and Blank Slate Brewing Company is here to do its part to grow that revolution.
</p>

<p>
Producing handcrafted, seasonal ales in small batches is what we're all about. We're creating both classical and innovative interpretations of the world's beer styles right here in Cincinnati, Ohio, one small batch at a time.
</p>
